title: Eyepoint Security
email: info@eyepoint-sec.com
description: We deliver the air-gap security for remote endpoints by ensuring data is only decrypted at the eye level.
baseurl: ""
domain: "eyepoint-sec.com"
url: "https://www.eyepoint-sec.com/"

theme: just-the-docs
logo: assets/logo.png
nav_enabled: false
search_enabled: false
heading_anchors: false

color_scheme: eyepoint

callouts_level: quiet
callouts:
  highlight:
    color: eyepoint

ga_tracking: G-MPGCF60N09
ga_tracking_anonymize_ip: true

exclude:
  - README.md
  - serve
  - "*.code-workspace"

sass:
  quiet_deps: true
  silence_deprecations: ['import']
